### ISSUE TITLE
Deno server not working on windows 10

### ISSUE THREAD

**Issue by Titos23** [googleanalytics/ga4-tutorials#6]
I installed deno using the powershell command. But when I type `deno task start` in the terminal, there is an error.

![image](https://user-images.githubusercontent.com/77001434/231469180-01e3dd7d-e6b5-4c4e-9115-a81a2634b37b.png)

**Comment by Titos23** [comment]
I have found a solution to my problem.

**Comment by Kallenju** [comment]
@Titos23 I have the same problem. How did you solve it? I use win 11.

Log:

Task start deno run -A --watch=src/public/ src/index.ts
Watcher Process started.
File server running on http://localhost:80/
index.eta
Error: The filename, directory name, or volume label syntax is incorrect. (os error 123): lstat 'C:\C:\Users\kosty\ga4-tutorials\src\public\index.eta'
    at Object.lstatSync (ext:deno_fs/30_fs.js:339:7)
    at Module.existsSync (https://deno.land/std@0.66.0/fs/exists.ts:23:10)
    at https://deno.land/x/eta@v1.11.0/file-utils.ts:113:19
    at Array.some (<anonymous>)
    at searchViews (https://deno.land/x/eta@v1.11.0/file-utils.ts:108:13)
    at getPath (https://deno.land/x/eta@v1.11.0/file-utils.ts:172:21)
    at renderFile (https://deno.land/x/eta@v1.11.0/file-handlers.ts:259:27)
    at handleHttp (file:///C:/Users/kosty/ga4-tutorials/src/index.ts:37:39)
    at eventLoopTick (ext:core/01_core.js:181:11) {
  code: "ENOENT"
}

**Comment by Titos23** [comment]
@Kallenju I didn't find a way to directly solve the issue. Instead I rewrote some of the website links and worked on localhost using the live server extension on VS Code. I can send you what I did if you need deep understanding.

**Comment by Kallenju** [comment]
@Titos23 Hi, I also opened an issue: https://github.com/googleanalytics/ga4-tutorials/issues/8

In the topic, I described how I solved the problem.

**Comment by matt-landers** [comment]
I just refactored a bit. Let me know if this is still an issue.
